### ISSUE TITLE
Crash on "Unknown interaction" error on `/bounty complete`

### ISSUE THREAD

**Issue by ntseng** [Imaginary-Horizons-Productions/BountyBot#172]
```
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/my_name_is_you_today/BountyBot/node_modules/@discordjs/rest/dist/index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/my_name_is_you_today/BountyBot/node_modules/@discordjs/rest/dist/index.js:826:23)
    at async _REST.request (/home/my_name_is_you_today/BountyBot/node_modules/@discordjs/rest/dist/index.js:1266:22)
    at async ChatInputCommandInteraction.reply (/home/my_name_is_you_today/BountyBot/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5) {
  requestBody: {
    files: [],
    json: {
      type: 4,
      data: {
        content: undefined,
        tts: false,
        nonce: undefined,        embeds: [          {
            color: 13421823,
            author: [Object],
            thumbnail: undefined,
            title: 'Water Wheels, Depots and Redstone. Oh my!',
            description: 'Join me as I stream some Minecraft Vaulthunters. Watch me flail about or help me figure out some of these cool machine type mod packs.',
            timestamp: '2024-02-10T04:10:44.085Z',
            footer: [Object],
            fields: [Array]
          }
        ],
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined,
        thread_name: undefined
      }
    }
  },
  rawError: { message: 'Unknown interaction', code: 10062 },  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1205727513071067216/aW50ZXJhY3Rpb246MTIwNTcyNzUxMzA3MTA2NzIxNjowUllzYTFkdjB0Z3NHVUpMaXVIRWdBVmFmWU1XN015aVJTWnNvQ052N2w4ZUZ1Y1JhaUpwMDhUNGdLelJCdElYR0t1SnVJZjZFdVpDNXJEV2hycE5zMmY1MEdmdXh6d1JxdkVmY012WjZhRDd6Tm1nN05iZ2VvYXRaNVFaTXRKSg/callback'
}
```

**Comment by ntseng** [comment]
This error can get thrown for two reasons:
1. Trying to acknowledge the same interaction twice (doesn't seem to be the case)
2. If an acknowledgement takes longer than 3 seconds to arrive, then arrives late
